language: node_js
os:
  - linux
node_js:
  - '14'
cache: yarn
notifications:
  email:
    - i91935058@gmail.com
script:
  - yarn global add codecov
  - yarn lint
  - yarn test
  - yarn build
after_success:
  - codecov
